### ISSUE TITLE
how return to initial read id ?

### ISSUE THREAD

**Issue by DelphIONe** [hammock-dev/hammock#5]
Hi,

I have one question again :-/
From the Hammock results, how can I recover for each peptide its id initial ? For example in alignments_final folder, I have *.aln files (=clusters). In each file, the sequences have been renamed as 0_1, 0_2, 0_3 etc (for the cluster 0). But I would like to know the correspondence between the old id (>M05379:44:000000000-JDBDF:1:1101:14629:1318) and the new id (type of >0_x), do you think it is possible ?

I didn't find this info in any output files, so maybe it's too difficult ?
Thanks again for your reply,

**Comment by krejciadam** [comment]
Hi!
  The original IDs are not returned, because by default, Hammock works with unique sequences only. So if there are multiple identical sequences in the input, Hammock only works with one of them. Then the output ID would be ambiguous. It would also not be correct to "clone back" the unique sequences in the output to match the number of input copies, because then e.g. sequence logos from these alignments would not really represent the clusters Hammock created. As I'm thinking of it, it might make sense to implement a "translation table" output that would facilitate mapping the ids back. Until then, I think string matching is the best thing to do. 

Adam

**Comment by DelphIONe** [comment]
Hi,

Thanks for your reply. I have developped one tiny script to do that.
