### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by eul2021** [hammock-dev/hammock#6]
Hello,
Apologies for a trivial question, but could you please provide exact installation instructions to build jars from the source code? Thank you very much.

**Comment by krejciadam** [comment]
Hi!
  To run Hammock, you should not need to install or build anything. The release archive contains an executable jar. 

If you really need to build the jar, you will just need the source code tarball and two Apache Commons libraries: 
commons-lang3-3.5
commons-math3-3.6.1
the jars for these libraries are in `dist/lib` folder of the release archive or here:
https://archive.apache.org/dist/commons/lang/binaries/ 
https://commons.apache.org/proper/commons-math/download_math.cgi

then I would recommend to use NetBeans IDE to open the project, add the two library jars and have the IDE build the jar for you. If you'd like to build from command line, please refer to java documentation on how to do it. Roughly, you'll need to change the `manifest.mf` file so that it contains this line:
`Main-Class: cz.krejciadam.hammock.Hammock`
and then the commands will be something like: 

```
mkdir dist
javac -d dist -cp /path/to/commons-lang3-3.5.jar:/path/to/commons-math3-3.6.1.jar src/cz/krejciadam/hammock/*.java
cd dist
jar cvmf ../manifest.mf Hammock.jar *
```

**Comment by krejciadam** [comment]
I'm closing this issue as there are no other questions.

**Comment by eul2021** [comment]
Thank you very much, this was helpful.
